### ISSUE TITLE
Generate badges via templating

### ISSUE THREAD

**Issue by ypid** [weareinteractive/gem-ansible-role#1]
Too much redundancy … :smile:
Example: https://github.com/nickjj/ansigenome/blob/954b67f1f739825bad862518cbbae20b746c3b9b/ansigenome/data/README.md.j2#L8

**Comment by ypid** [comment]
See also: https://github.com/ypid/dotfiles/blob/1f6fc973544ac294a430d07d110cc37ec6507c45/.ansigenome/ypid.README.md.j2#L6-L18

**Comment by franklinkim** [comment]
Well, I always use travis and I also spent some time to implement the usage of the new docker feature. So it should be used. And yes, this is work in progress and I wasn't sure if I should force my badges... maybe I should for the beginning...

**Comment by franklinkim** [comment]
Will leave as is for now
