### ISSUE TITLE
Different goals than ansigenome.

### ISSUE THREAD

**Issue by ypid** [weareinteractive/gem-ansible-role#2]
It seems that ansigenome did not fit your needs. What was it that you needed that ansigenome could not offer? Probably:

> Since I manage multiple roles from multiple clients and sources I would need it to be on a per role basis. Thus also ensuring that if someone else forks my role he can generate the same README file.

Maybe ansigenome can be extended to include the template into the role …

Related to: https://github.com/weareinteractive/ansible-cron/issues/3#issuecomment-138862827

**Comment by franklinkim** [comment]
You might be able to do that but besided the template it also needs a config file i.e.:

```
# Access a single author (taken from your config).
author.name
author.company
author.url
author.email
author.twitter
author.github
```

It definitely means a lot of refactoring to make it available on a per role basis since it wasn't made for that and a some tools like `run` or `export` wouldn't make sense in a single role...

**Comment by ypid** [comment]
All right. At least the author(s) can be specified in the ansigenome.yml as well.
